// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitializeBar - функция для инициализации Bar
func InitializeBar() string {
	myFooer := provideMyFooer()
	string2 := provideBar(myFooer)
	return string2
}
