// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: api/dump-collector.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_SUBSCRIBE   OperationType = 0 // Значение по умолчанию
	OperationType_UNSUBSCRIBE OperationType = 1
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "SUBSCRIBE",
		1: "UNSUBSCRIBE",
	}
	OperationType_value = map[string]int32{
		"SUBSCRIBE":   0,
		"UNSUBSCRIBE": 1,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_dump_collector_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_api_dump_collector_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_api_dump_collector_proto_rawDescGZIP(), []int{0}
}

// Запрос для подписки
type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupportedTypes []string `protobuf:"bytes,1,rep,name=supported_types,json=supportedTypes,proto3" json:"supported_types,omitempty"` // Список типов поддерживаемых идентификаторов
	ServiceType    string   `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`          // Тип сервиса
	NodeName       string   `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`                   // Имя ноды
	LinkType       *uint32  `protobuf:"varint,4,opt,name=linkType,proto3,oneof" json:"linkType,omitempty"`                            // LinkType для Dump Header
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_dump_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dump_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_dump_collector_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSupportedTypes() []string {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

func (x *SubscribeRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *SubscribeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *SubscribeRequest) GetLinkType() uint32 {
	if x != nil && x.LinkType != nil {
		return *x.LinkType
	}
	return 0
}

// Нотификация о состоянии абонента на трейсе
type TraceNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Traces        []*Trace      `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	OperationType OperationType `protobuf:"varint,2,opt,name=operationType,proto3,enum=dumpcollector.OperationType" json:"operationType,omitempty"`
}

func (x *TraceNotification) Reset() {
	*x = TraceNotification{}
	mi := &file_api_dump_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceNotification) ProtoMessage() {}

func (x *TraceNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_dump_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceNotification.ProtoReflect.Descriptor instead.
func (*TraceNotification) Descriptor() ([]byte, []int) {
	return file_api_dump_collector_proto_rawDescGZIP(), []int{1}
}

func (x *TraceNotification) GetTraces() []*Trace {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *TraceNotification) GetOperationType() OperationType {
	if x != nil {
		return x.OperationType
	}
	return OperationType_SUBSCRIBE
}

type Trace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_api_dump_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_api_dump_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_api_dump_collector_proto_rawDescGZIP(), []int{2}
}

func (x *Trace) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Trace) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DumpPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packets []*PacketData `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	Type    string        `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`   // тип UE
	Value   string        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // значение UE
}

func (x *DumpPackage) Reset() {
	*x = DumpPackage{}
	mi := &file_api_dump_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpPackage) ProtoMessage() {}

func (x *DumpPackage) ProtoReflect() protoreflect.Message {
	mi := &file_api_dump_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpPackage.ProtoReflect.Descriptor instead.
func (*DumpPackage) Descriptor() ([]byte, []int) {
	return file_api_dump_collector_proto_rawDescGZIP(), []int{3}
}

func (x *DumpPackage) GetPackets() []*PacketData {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *DumpPackage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DumpPackage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PacketData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Ма
	// ссив байт
	ReceiveTime int64 `protobuf:"varint,2,opt,name=receiveTime,proto3" json:"receiveTime,omitempty"`
}

func (x *PacketData) Reset() {
	*x = PacketData{}
	mi := &file_api_dump_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketData) ProtoMessage() {}

func (x *PacketData) ProtoReflect() protoreflect.Message {
	mi := &file_api_dump_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketData.ProtoReflect.Descriptor instead.
func (*PacketData) Descriptor() ([]byte, []int) {
	return file_api_dump_collector_proto_rawDescGZIP(), []int{4}
}

func (x *PacketData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PacketData) GetReceiveTime() int64 {
	if x != nil {
		return x.ReceiveTime
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*Request_Request
	//	*Request_Package
	Data isRequest_Data `protobuf_oneof:"data"`
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_dump_collector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_dump_collector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_dump_collector_proto_rawDescGZIP(), []int{5}
}

func (m *Request) GetData() isRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Request) GetRequest() *SubscribeRequest {
	if x, ok := x.GetData().(*Request_Request); ok {
		return x.Request
	}
	return nil
}

func (x *Request) GetPackage() *DumpPackage {
	if x, ok := x.GetData().(*Request_Package); ok {
		return x.Package
	}
	return nil
}

type isRequest_Data interface {
	isRequest_Data()
}

type Request_Request struct {
	Request *SubscribeRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type Request_Package struct {
	Package *DumpPackage `protobuf:"bytes,2,opt,name=package,proto3,oneof"`
}

func (*Request_Request) isRequest_Data() {}

func (*Request_Package) isRequest_Data() {}

var File_api_dump_collector_proto protoreflect.FileDescriptor

var file_api_dump_collector_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x75, 0x6d, 0x70, 0x2d, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x64, 0x75, 0x6d, 0x70,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xa9, 0x01, 0x0a, 0x10, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27,
	0x0a, 0x0f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x69, 0x6e,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x69, 0x6e,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x63, 0x65, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x06, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x75,
	0x6d, 0x70, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x52, 0x06, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x0d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x64, 0x75, 0x6d, 0x70, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x31, 0x0a,
	0x05, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x6c, 0x0a, 0x0b, 0x44, 0x75, 0x6d, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12,
	0x33, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x64, 0x75, 0x6d, 0x70, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x42,
	0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x64, 0x75, 0x6d, 0x70, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64,
	0x75, 0x6d, 0x70, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x75, 0x6d,
	0x70, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x2f, 0x0a, 0x0d, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55,
	0x4e, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x01, 0x32, 0x68, 0x0a, 0x14,
	0x44, 0x75, 0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x54, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x64, 0x75, 0x6d, 0x70, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x64, 0x75, 0x6d, 0x70, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_dump_collector_proto_rawDescOnce sync.Once
	file_api_dump_collector_proto_rawDescData = file_api_dump_collector_proto_rawDesc
)

func file_api_dump_collector_proto_rawDescGZIP() []byte {
	file_api_dump_collector_proto_rawDescOnce.Do(func() {
		file_api_dump_collector_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_dump_collector_proto_rawDescData)
	})
	return file_api_dump_collector_proto_rawDescData
}

var file_api_dump_collector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_dump_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_dump_collector_proto_goTypes = []any{
	(OperationType)(0),        // 0: dumpcollector.OperationType
	(*SubscribeRequest)(nil),  // 1: dumpcollector.SubscribeRequest
	(*TraceNotification)(nil), // 2: dumpcollector.TraceNotification
	(*Trace)(nil),             // 3: dumpcollector.Trace
	(*DumpPackage)(nil),       // 4: dumpcollector.DumpPackage
	(*PacketData)(nil),        // 5: dumpcollector.PacketData
	(*Request)(nil),           // 6: dumpcollector.Request
}
var file_api_dump_collector_proto_depIdxs = []int32{
	3, // 0: dumpcollector.TraceNotification.traces:type_name -> dumpcollector.Trace
	0, // 1: dumpcollector.TraceNotification.operationType:type_name -> dumpcollector.OperationType
	5, // 2: dumpcollector.DumpPackage.packets:type_name -> dumpcollector.PacketData
	1, // 3: dumpcollector.Request.request:type_name -> dumpcollector.SubscribeRequest
	4, // 4: dumpcollector.Request.package:type_name -> dumpcollector.DumpPackage
	6, // 5: dumpcollector.DumpCollectorService.SubscribeToTrace:input_type -> dumpcollector.Request
	2, // 6: dumpcollector.DumpCollectorService.SubscribeToTrace:output_type -> dumpcollector.TraceNotification
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_dump_collector_proto_init() }
func file_api_dump_collector_proto_init() {
	if File_api_dump_collector_proto != nil {
		return
	}
	file_api_dump_collector_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_dump_collector_proto_msgTypes[5].OneofWrappers = []any{
		(*Request_Request)(nil),
		(*Request_Package)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_dump_collector_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dump_collector_proto_goTypes,
		DependencyIndexes: file_api_dump_collector_proto_depIdxs,
		EnumInfos:         file_api_dump_collector_proto_enumTypes,
		MessageInfos:      file_api_dump_collector_proto_msgTypes,
	}.Build()
	File_api_dump_collector_proto = out.File
	file_api_dump_collector_proto_rawDesc = nil
	file_api_dump_collector_proto_goTypes = nil
	file_api_dump_collector_proto_depIdxs = nil
}
