version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # Проброс порта 4222 для NATS
      - "8222:8222"  # Проброс порта 8222 для мониторинга
    restart: always

  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4223:4222"  # Проброс порта 4223 для NATS Streaming
    environment:
      - NATS_URL=nats:4222  # Указываем URL NATS сервера
      - CLUSTER_ID=test-cluster  # Указываем идентификатор кластера
    restart: always

  nats-streaming-ui:
    image: piotrpersona/nats-streaming-ui:latest
    ports:
      - "8282:8282"  # Проброс порта 8282 для UI
    environment:
      - STAN_URL=nats-streaming:4223  # URL NATS Streaming
      - STAN_MONITOR_URL=nats:8222  # URL мониторинга NATS
      - STAN_CLUSTER=test-cluster  # Идентификатор кластера
    restart: always
    depends_on:
      - nats-streaming  # Зависимость от nats-streaming
